### ISSUE TITLE
Interpretare i dati da inserire. 

### ISSUE THREAD

**Issue by ninoger** [RedFoxy/HA-Tank-Level-Sensor#1]
Ciao, ho costruito due sensori seguendo le istruzioni, versione senza led e sensore impermeabile, ed entrambi funzionano molto bene. Chiedo una semplice spiegazione dei dati della cisterna. Casualmente sono molto simili alle dimensioni delle mie ma vorrei affinare le misure, ma non ne comprendo il significato, a parte i litri. Grazie molte.

**Comment by RedFoxy** [comment]
Ciao
Quale dato non capisci?
C'è il Volume in Litri, la distanza dal sensore in cm e quanto è pieno in %

**Comment by ninoger** [comment]
Ciao RedFoxy,
grazie per la risposta e mi scuso, ma ho letto solo adesso il tuo commento. Dunque, i dati di default del codice sono questi:

min_sensor:    "2048"   # Minimum distance from ultrasonic sensor, note that JSN-SR04T can't read less than 20cm!
max_sensor:    "10700"  # Maximum distance inside the tank
tank_capacity: "1500"   # Maximum Tank volume in liters

Quello che non capisco sono le unità di misura utilizzate, perchè se il primo dato, 2048, fosse in centimetri sarebbero 20,48 metri; se in millimetri 2,048 metri. Lo stesso per il secondo dato, 10700, per la distanza. Invece l'ultimo dato per me è comprensibile, cioè 1500 litri. Perdonami, ma certamente si tratta di un mio limite ma davvero non comprendo i primi due. Per il resto tutto funziona a perfezione e posso usare i sensori anche coi dati di default, visto che si tratta di misure molto simili ai miei serbatoi. Come detto, vorrei semplicemente affinare le misure.
Grazie per il progetto e grazie per la risposta.
Un saluto.

**Comment by RedFoxy** [comment]
Ciao!
Quelli non sono dati di default, ma sono i miei dati :)
Li ho impostati leggendo i valori del sensore quando il serbatoio era pieno (min_sensor) e vuoto (max_sensor), mentre tank_capacity è il valore (teorico) della capacità del seratoio.

**Comment by ninoger** [comment]
Ciao.
Ok, ma per esempio, 2048 che numero è? Così come 10700. 1500 l'ho capito che sono i litri, dunque la capacità della cisterna. Credimi, non riesco a comprenderli i primi due.
Grazie

**Comment by RedFoxy** [comment]
2048 mm

**Comment by ninoger** [comment]
Ma 2048 mm non equivale a 2,048 metri? Comunque, come detto, il sensore funziona.

**Comment by RedFoxy** [comment]
si scusa sbagliato io 20,48 cm

**Comment by ninoger** [comment]
Quindi, in sostanza, quei numeri non sono standard, per così dire. E 10700 sta per 1,07 metri o cosa? Su quale calcolo matematico si basano? Come già detto, l'unico dato che mi è chiaro è 1500 litri.
Grazie.

**Comment by RedFoxy** [comment]
si 107cm o 1,07 metri, non sono calcolati quelli, semplicemente dopo che ho messo il sensore ho misurato la distanza con il metro e con il sensore, il risultato era molto simile, ho qundi messo il valore preso dal sensore a serbatoio preso e l'ho messo nella variabile max_sensor, ho quindi riempito il serbatoio, visto che mi dava errori il sensore sotto i 2048 (20,48cm) per via del fatto che il sensore non misura sotto i 20cm e per la qualità del sensore, ho deciso di mettere quel valore come valore tecnico di serbatoio pieno, in ogni caso il valore di serbatoio pieno non lo uso per mission critical tipo chiudere l'acqua o altro ma solo per avere una stima abbastanza veritiera sulla quantità presente nel serbatoio, mentre tutti gli altri valori calcolati sono solo il calcolo del volume per avere i litri dentro il serbatoio, la percentuale di quanta acqua c'è etc... ma sono tutti basati su min/max impostati dal sensore.

Inoltre tieni conto di un fattore fondamentale, l'acqua dentro il serbatoio spesso NON è statica, quando scarichi o carichi l'acqua, la superfice si increspa e questo genera errori di lettura, se poi hai il serbatoio all'esterno, come me, anche gli agenti atmosferici possono alterare il movimento dell'acqua generandoti errori di lettura

**Comment by ninoger** [comment]
Perfetto. A questo punto, se ho ben compreso, per affinare il più possibile le misure, dovrò cercare di allontanare il sensore di circa 1 cm, in quanto adesso sono entrambi a circa 19 cm quando il serbatoio è completamente pieno. Infatti man mano che si svuotano comincia a misurare, secondo me, correttamente, anche se non so se in effetti i litri che mancano sono proprio quelli che segna, ma sicuramente non sono numeri sballati. Posso arrivarci in maniera empirica. Comunque grazie per il progetto. In ogni caso mi è molto utile.

**Comment by RedFoxy** [comment]
Ottimo! Se hai bisogno, scrivimi pure!
